# Generated by Django 4.2.7 on 2025-07-07 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('question_type', models.CharField(choices=[('choice', '選択問題'), ('essay', '記述問題'), ('table', '表作成問題'), ('highlight', 'ハイライト問題')], max_length=20, verbose_name='問題タイプ')),
                ('order', models.IntegerField(default=1, verbose_name='順序')),
                ('hide_text', models.BooleanField(default=False, verbose_name='文章を隠す')),
                ('allow_notes_only', models.BooleanField(default=False, verbose_name='メモのみ参照可能')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='選択肢')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('order', models.IntegerField(default=1, verbose_name='順序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cbt_app.question')),
            ],
            options={
                'verbose_name': '選択肢',
                'verbose_name_plural': '選択肢',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='StudentAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.IntegerField(verbose_name='開始位置')),
                ('end_position', models.IntegerField(verbose_name='終了位置')),
                ('annotation_type', models.CharField(choices=[('highlight', 'ハイライト'), ('note', '注釈'), ('memo', 'メモ')], max_length=20, verbose_name='注釈タイプ')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '生徒注釈',
                'verbose_name_plural': '生徒注釈',
            },
        ),
        migrations.CreateModel(
            name='StudentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50, verbose_name='活動タイプ')),
                ('details', models.JSONField(default=dict, verbose_name='詳細情報')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.question', verbose_name='対象問題')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '生徒活動ログ',
                'verbose_name_plural': '生徒活動ログ',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章'),
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, verbose_name='回答内容')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='提出済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.question', verbose_name='問題')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.questionchoice', verbose_name='選択した選択肢')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
            ],
            options={
                'verbose_name': '生徒回答',
                'verbose_name_plural': '生徒回答',
                'unique_together': {('student', 'question')},
            },
        ),
    ]
