# Generated by Django 4.2.7 on 2025-07-11 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('question_type', models.CharField(choices=[('choice', '選択問題'), ('essay', '記述問題'), ('table', '表作成問題'), ('highlight', 'ハイライト問題')], max_length=20, verbose_name='問題タイプ')),
                ('order', models.IntegerField(default=1, verbose_name='順序')),
                ('hide_text', models.BooleanField(default=False, verbose_name='文章を隠す')),
                ('allow_notes_only', models.BooleanField(default=False, verbose_name='メモのみ参照可能')),
                ('show_in_answering_phase', models.BooleanField(default=True, verbose_name='解答フェーズで表示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='選択肢')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('order', models.IntegerField(default=1, verbose_name='順序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cbt_app.question')),
            ],
            options={
                'verbose_name': '選択肢',
                'verbose_name_plural': '選択肢',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.IntegerField(verbose_name='開始位置')),
                ('end_position', models.IntegerField(verbose_name='終了位置')),
                ('annotation_type', models.CharField(choices=[('highlight', 'ハイライト'), ('note', '注釈'), ('memo', 'メモ')], max_length=20, verbose_name='注釈タイプ')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '生徒注釈',
                'verbose_name_plural': '生徒注釈',
            },
        ),
        migrations.CreateModel(
            name='StudentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50, verbose_name='活動タイプ')),
                ('details', models.JSONField(default=dict, verbose_name='詳細情報')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.question', verbose_name='対象問題')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '生徒活動ログ',
                'verbose_name_plural': '生徒活動ログ',
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.CharField(choices=[('reading', '読解フェーズ'), ('answering', '解答フェーズ'), ('completed', '完了')], default='reading', max_length=20, verbose_name='現在のフェーズ')),
                ('reading_start_time', models.DateTimeField(auto_now_add=True, verbose_name='読解開始時刻')),
                ('reading_end_time', models.DateTimeField(blank=True, null=True, verbose_name='読解終了時刻')),
                ('answering_start_time', models.DateTimeField(blank=True, null=True, verbose_name='解答開始時刻')),
                ('answering_end_time', models.DateTimeField(blank=True, null=True, verbose_name='解答終了時刻')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '読解セッション',
                'verbose_name_plural': '読解セッション',
                'unique_together': {('student', 'text')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章'),
        ),
        migrations.CreateModel(
            name='ActiveReadingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('logic-structure', '論理構造分析'), ('causal-map', '因果関係マップ'), ('concept-map', '概念マップ'), ('argument-analysis', '論証構造分析'), ('perspective-analysis', '多角的視点分析')], max_length=30, verbose_name='コンテンツタイプ')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('data', models.JSONField(default=dict, verbose_name='分析データ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '積極的読み分析',
                'verbose_name_plural': '積極的読み分析',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserParagraphDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.IntegerField(verbose_name='段落番号')),
                ('content', models.TextField(verbose_name='段落内容')),
                ('start_offset', models.IntegerField(verbose_name='開始位置')),
                ('end_offset', models.IntegerField(verbose_name='終了位置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': 'ユーザー定義段落',
                'verbose_name_plural': 'ユーザー定義段落',
                'ordering': ['paragraph_number'],
                'unique_together': {('student', 'text', 'paragraph_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, verbose_name='回答内容')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='提出済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.question', verbose_name='問題')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.questionchoice', verbose_name='選択した選択肢')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
            ],
            options={
                'verbose_name': '生徒回答',
                'verbose_name_plural': '生徒回答',
                'unique_together': {('student', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, verbose_name='回答内容')),
                ('confidence_level', models.IntegerField(default=3, verbose_name='確信度（1-5）')),
                ('response_time', models.DurationField(blank=True, null=True, verbose_name='回答時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.question', verbose_name='問題')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.questionchoice', verbose_name='選択した選択肢')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.readingsession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': '問題回答',
                'verbose_name_plural': '問題回答',
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ParagraphSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.IntegerField(verbose_name='段落番号')),
                ('original_content', models.TextField(verbose_name='元の段落内容')),
                ('summary', models.TextField(blank=True, verbose_name='要旨')),
                ('keywords', models.JSONField(default=list, verbose_name='キーワード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '段落要旨',
                'verbose_name_plural': '段落要旨',
                'unique_together': {('student', 'text', 'paragraph_number')},
            },
        ),
        migrations.CreateModel(
            name='ConceptMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_data', models.JSONField(default=dict, verbose_name='マップデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '概念マップ',
                'verbose_name_plural': '概念マップ',
                'unique_together': {('student', 'text')},
            },
        ),
        migrations.CreateModel(
            name='ComparisonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_data', models.JSONField(default=dict, verbose_name='表データ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '比較表',
                'verbose_name_plural': '比較表',
                'unique_together': {('student', 'text')},
            },
        ),
        migrations.CreateModel(
            name='ArgumentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claims', models.JSONField(default=list, verbose_name='主張')),
                ('evidence', models.JSONField(default=list, verbose_name='根拠')),
                ('conclusions', models.JSONField(default=list, verbose_name='結論')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '論証構造',
                'verbose_name_plural': '論証構造',
                'unique_together': {('student', 'text')},
            },
        ),
    ]
