# Generated by Django 4.2.7 on 2025-07-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ユーザープロファイル', 'verbose_name_plural': 'ユーザープロファイル'},
        ),
    ]
