# Generated by Django 4.2.7 on 2025-07-10 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.IntegerField(verbose_name='段落番号')),
                ('original_content', models.TextField(verbose_name='元の段落内容')),
                ('summary', models.TextField(blank=True, verbose_name='要旨')),
                ('keywords', models.JSONField(default=list, verbose_name='キーワード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '段落要旨',
                'verbose_name_plural': '段落要旨',
                'unique_together': {('student', 'text', 'paragraph_number')},
            },
        ),
        migrations.CreateModel(
            name='ConceptMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_data', models.JSONField(default=dict, verbose_name='マップデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '概念マップ',
                'verbose_name_plural': '概念マップ',
                'unique_together': {('student', 'text')},
            },
        ),
        migrations.CreateModel(
            name='ComparisonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_data', models.JSONField(default=dict, verbose_name='表データ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '比較表',
                'verbose_name_plural': '比較表',
                'unique_together': {('student', 'text')},
            },
        ),
        migrations.CreateModel(
            name='ArgumentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claims', models.JSONField(default=list, verbose_name='主張')),
                ('evidence', models.JSONField(default=list, verbose_name='根拠')),
                ('conclusions', models.JSONField(default=list, verbose_name='結論')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '論証構造',
                'verbose_name_plural': '論証構造',
                'unique_together': {('student', 'text')},
            },
        ),
    ]
