# Generated by Django 4.2.7 on 2025-07-10 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbt_app', '0002_paragraphsummary_conceptmap_comparisontable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveReadingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('logic-structure', '論理構造分析'), ('causal-map', '因果関係マップ'), ('concept-map', '概念マップ'), ('argument-analysis', '論証構造分析'), ('perspective-analysis', '多角的視点分析')], max_length=30, verbose_name='コンテンツタイプ')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('data', models.JSONField(default=dict, verbose_name='分析データ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '積極的読み分析',
                'verbose_name_plural': '積極的読み分析',
                'ordering': ['-created_at'],
            },
        ),
    ]
