# Generated by Django 4.2.7 on 2025-07-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0002_alter_userprofile_options'),
    ]

    operations = [
    ]
