# Generated by Django 4.2.7 on 2025-07-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbt_app', '0003_activereadingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserParagraphDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.IntegerField(verbose_name='段落番号')),
                ('content', models.TextField(verbose_name='段落内容')),
                ('start_offset', models.IntegerField(verbose_name='開始位置')),
                ('end_offset', models.IntegerField(verbose_name='終了位置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': 'ユーザー定義段落',
                'verbose_name_plural': 'ユーザー定義段落',
                'ordering': ['paragraph_number'],
                'unique_together': {('student', 'text', 'paragraph_number')},
            },
        ),
    ]
