# Generated by Django 4.2.7 on 2025-07-10 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbt_app', '0004_userparagraphdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.CharField(choices=[('reading', '読解フェーズ'), ('answering', '解答フェーズ'), ('completed', '完了')], default='reading', max_length=20, verbose_name='現在のフェーズ')),
                ('reading_start_time', models.DateTimeField(auto_now_add=True, verbose_name='読解開始時刻')),
                ('reading_end_time', models.DateTimeField(blank=True, null=True, verbose_name='読解終了時刻')),
                ('answering_start_time', models.DateTimeField(blank=True, null=True, verbose_name='解答開始時刻')),
                ('answering_end_time', models.DateTimeField(blank=True, null=True, verbose_name='解答終了時刻')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.text', verbose_name='対象文章')),
            ],
            options={
                'verbose_name': '読解セッション',
                'verbose_name_plural': '読解セッション',
                'unique_together': {('student', 'text')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, verbose_name='回答内容')),
                ('confidence_level', models.IntegerField(default=3, verbose_name='確信度（1-5）')),
                ('response_time', models.DurationField(blank=True, null=True, verbose_name='回答時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.question', verbose_name='問題')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.questionchoice', verbose_name='選択した選択肢')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt_app.readingsession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': '問題回答',
                'verbose_name_plural': '問題回答',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
